---
title: "Group 5 Lab 2"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
team members: Ian Cornish, Taylor Rouse, and Barrett Hill

github repo: https://github.com/icornish97/lab2

## Question set #1 (Group)

1. There were 1852 chocolate bars reviewed 
2. The number of ratings gradually increases until  the year of 2016 where we see a continual decrease in the number of ratings though the present.

```{R}
library(ggplot2)
choco <- read.csv("https://ds202-at-isu.github.io/labs/data/choco.csv")
head(choco)
ggplot(aes(x = Review.Date),data = choco) + geom_bar()
```
## Question set #2 (Individual)
1. The distribution of the ratings is unimodal and fairly symmetric. There are outliers above at 5, and below at 1 and 1.5. The median appears to be about 3 or 3.25.
```{R}
ggplot(data = choco, aes(x = Rating)) +
  geom_histogram(binwidth = .25)
```

2.From what we have observed there is not a significant impact on the rating of the chocolate based on the cocoa percentage. That being said there were some interesting observations worth noting. 
 + No chocolate with a 90% cocoa percentage or above had a 4 or higher rating. 
 + The higher the rating the tighter the distribution of cocoa percentage got to 70%. 
 + The only five star rating had a cocoa percentage of 70%
 + One of the chocolates that recieved a one star ratings also had a cocoa percentage of 70%
 
```{R}
ggplot(aes(x=Rating, y = Cocoa.Pct), data = choco) + geom_point()
```

3. Across the different company locations in the top 3 countries with the most ratings The USA has a significant greater amount of ratings compared to France and Canada which are similar. France and Canada have between 100 and 200 ratings while the USA has almost 800
```{R}
Top3<- dplyr::filter(choco, Company.Location %in% c("U.S.A.", "France", "Canada"))
ggplot(data=Top3, aes(x=Company.Location))+geom_bar()
```
##Paragraph 

Our team was able to use github in order to aid our workflow. We were able to collaborate on the group questions in person which was very easy. When we moved on to the individual questions we assigned each member of our group one question to complete. We were all able to complete the tasks that we were assigned and commit our changes to the github repository. Overall github was a fast and easy way to finish a group task!  
